const os = require("os");
console.log(os.totalmem());
console.log(os.freemem());
console.log(os.arch());
console.log(os.cpus());
console.log(os.tmpdir());
console.log(os.homedir());
console.log(os.hostname());
console.log(os.userInfo());
console.log(os.networkInterfaces());